defaultSemverRangePrefix: ''

enableScripts: false

logFilters:
  - level: discard
    pattern: '* this makes the require call ambiguous and unsound.'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

pnpMode: loose

supportedArchitectures:
  os:
    - linux

yarnPath: .yarn/releases/yarn-3.2.2.cjs
