version: '3.8'

services:
  build:
    image: ghcr.io/chnapy/bloup/api-staging
    environment:
      - NODE_ENV=staging
      - PORT=3333
      - DB_URL=mongodb://mongodb/bloup-staging
      - GOOGLE_CLIENT_ID # secret
    build:
      context: ../../../..
      dockerfile: packages/api/environment/staging/Dockerfile.staging
    ports:
      - '3333:3333'
    networks:
      - api
    depends_on:
      - mongodb
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      # Send GraphQL introspection query
      # During healthcheck, 'nameservice' hosts are not yet defined, so localhost is used instead
      test:
        [
          'CMD',
          'curl',
          '--fail',
          'http://localhost:3333/graphql',
          '--data-raw',
          '{ "operationName": "IntrospectionQuery", "query": "query IntrospectionQuery { __schema { queryType { name } } }", "variables": {} }',
          '-H',
          'content-type: application/json',
        ]
      interval: 20s
      timeout: 5s
      retries: 4

  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="bloup-staging"
    ports:
      - '37017:27017'
    networks:
      - api
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

networks:
  api:

volumes:
  mongodb:
  mongodb_config:
