version: '3.8'

services:
  build:
    image: ghcr.io/chnapy/bloup/api-staging
    # container_name: bloup.api-staging.main
    environment:
      - NODE_ENV=staging
      - PORT=3333
      - DB_URL=mongodb://mongodb/bloup-staging
    build:
      context: ../../../..
      dockerfile: packages/api/environment/staging/Dockerfile.staging
    labels:
      - org.opencontainers.image.source=https://github.com/chnapy/bloup
    ports:
      - '80:3333'
    depends_on:
      - mongodb
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: 'curl --fail http://build:80/graphql'
      interval: 30s
      timeout: 10s
      retries: 4

  mongodb:
    image: mongo:latest
    # container_name: bloup.api-staging.mongodb
    environment:
      - MONGODB_DATABASE="bloup-staging"
    ports:
      - '37017:27017'
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

volumes:
  mongodb:
  mongodb_config:
