version: '3.8'

services:
  build:
    image: ghcr.io/chnapy/bloup/web-app-staging
    environment:
      - NODE_ENV=staging
    build:
      context: ../../../..
      dockerfile: packages/web-app/environment/staging/Dockerfile.staging
    ports:
      - '80:80'
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: 'curl --fail http://localhost:80'
      interval: 20s
      timeout: 5s
      retries: 4
