name: PR packages labeler

on:
  pull_request:
    types: [opened]

jobs:
  labelPR:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - name: Label PR with packages
        uses: tinkurlab/monorepo-pr-labeler-action@3.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_DIRS: 'packages'
        with:
          prefix: '🗂 '
